@startuml Авторизация внешней платформы

|User|
start
:Вход в игру;
|Game|
    repeat
        :Показ доступных
        внешних провайдеров;
        |User|
        :Выбор провайдера;
        |Game|
        :Авторизация в выбранном
        провайдере;
        :Отправка AuthPayload
        для получения токена
        сессии;
        |Backend|
        :Валидация AuthPayload;
        if (Валидация успешная?) then (+)
            :Создание новой сессии;
            :Статус 200 токеном сессии;
        else (-)
            :Статус 422;
        endif
        :Отправка ответа;
        |Game|
    repeat while (Запрос успешный?) is (-) not (+)
:Сохранение токена сессии;
:Старт игровой логики;

stop

@enduml
