@startuml Авторизация внутренней платформы(классика жанра)

|Game|
start
    note left
        Подразумевается что игрок
        пребывает в рамках какой-либо
        платформы (соц-сеть, нативка,
        или ещё где-нибудь там..),
        то есть как минимум там, где
        известен его userId
    end note
    :Отправка AuthPayload
    для получения токена
    сессии;
    |Backend|
    :Валидация AuthPayload;
    if (Валидация успешная?) then (+)
        :Создание новой сессии;
        :Статус 200 токеном сессии;
    else (-)
        :Статус 422;
    endif
    :Отправка ответа;
    |Game|
    if (Запрос успешный?) then (+)
        :Сохранение токена сессии;
    else (-)
        :Досведание;
        end
    endif
    :Старт игровой логики;
stop

@enduml
