@startuml Диаграмма активности процесса миграции в cross-stitch-cocos(все платформы)

|Игрок|
start

:Запуск игры;
|Frontend|
:Запрос незавершенной миграции;
note right
То есть той, в которой либо:
-незавершена миграция данных игрока
-незавершена миграция предметов игрока
-незавершена миграция библиотеки игрока
end note
|Backend|
:Отправка незавершенной миграции;
|Frontend|
if (Есть незавершенная миграция?) then (Нет)
    :Запрос списка доступных \nданных для миграции;
    |Backend|
    :Отправка списка доступных \nданных для миграции;
    note right
        Важный момент! 
        Берутся записи из коллекции user-plaforms
        и далее по ним сопоставляются legacy платформы
        и userId, после чего делается запрос по каждой
        полученной платформе в legacy БД
        В случае FB-Instant клиент игры во время
        авторизации шлёт AuthPayload с подмешанным свойством
        externalPlatforms: {key: string, userId: string}[].
        Далее обработчик пост-авторизации добавляет эти
        платформы в user-plaforms при условии что они уникальны
        Поэтому в случае нативок можно брать legacy userId
        из localStorage и отправлять его в externalPlatforms,
        после чего он попадет в коллекцию user-plaforms,
        по которой уже сервис миграции вытащит legacy прогресс.
    end note
    |Frontend|
    if (Список пустой?) then (Нет)
        :Проверка количества прогрессов;
        note
            Если прогресс один то миграция будет
            принудительной(в случае соц-сетей ВК и ОДК)
            В FB-instant может быть несколько прогрессов:
            legacy FB-Instant и FB-Canvas
        end note
        if (Прогресс 1?) then (Да)
        else (Нет)
            :Показ окна со списком доступных \nданных для миграции;
            |Игрок|
            :Выбор данных;
            |Frontend|
            if (Данные выбраны?) then (Да)
                |Игрок|
                :Подтверждение операции;
                note left
                    Ввод pin-кода
                end note
                |Frontend|
                if (Подтверждение успешное?) then (Да)
                else (Нет)
                    end
                endif
            else (Нет)
            endif
        endif
        :Отправка запроса на создание миграции;
        |Backend|
        :Резервное копирование(backup)
        данных игрока;
        note 
            Чтобы потом можно было
            восстановить их через админку
            или через клиент игры в dev mode
        end note
        :Сброс данных игрока;
        :Создание записи миграции в базе;
        |Frontend|
    else (Да)
    endif
else (Да)
endif
:Запуск процесса миграции;
:Старт игры;
stop

|Frontend|
rectangle "Процесс миграции" {
    start
}
:Чтении записи миграции;
if (Данные игрока мигрированы?) then (Нет)
    :Запрос на миграцию \nданных игрока;
    |Backend|
    :Миграция данных игрока;
    note right
    Данных из коллеций
    users
    end note
    :Отметка о миграции данных игрока
    в записи миграции;
    |Frontend|
else (Да)
endif
:Чтении записи миграции;
if (Предметы игрока мигрированы?) then (Нет)
    |Frontend|
    :Запрос на миграцию \nпредметов игрока;
    |Backend|
    :Миграция предметов игрока;
    note right
    Данных из коллеций
    user-items
    end note
    :Отметка о миграции предметов игрока
    в записи миграции;
    |Frontend|
else (Да)
endif
:Чтении записи миграции;
if (Библиотека мигрирована?) then (Нет)
    :Запрос на получение идентификаторов
    картинок для миграции;
    |Backend|
    :Отправка идентификаторов
    оставшихся картинок для миграции;
    |Frontend|
    :Показ окна с прогрессом
    миграции картинок;
    repeat
        :Миграция до 50 картинок;
        |Backend|
        :Миграция картинок;
        |Frontend|
    repeat while (Есть ли ещё картинки?)
    :Запрос на завершение миграции;
    |Backend|
    :Отметка о миграции картинок
    в записи миграции;
    |Frontend|
    :Закрытие окна с прогрессом
    миграции картинок;
else (Да)
endif
:Чтении записи миграции;
if (Платежи игрока мигрированы?) then (Нет)
    |Frontend|
    :Запрос на миграцию \n платежей игрока;
    |Backend|
    :Миграция платежей игрока;
    note right
    Данных из коллеций
    payments
    end note
    :Отметка о миграции платежей игрока
    в записи миграции;
    |Frontend|
else (Да)
endif
stop

@enduml
